DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  CONSTRAINT pk_users PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email)
);
COMMENT ON TABLE users IS 'Таблица пользователей';
COMMENT ON COLUMN users.id IS 'Идентификатор записи';
COMMENT ON COLUMN users.name IS 'Имя пользователя';
COMMENT ON COLUMN users.email IS 'Почтовый адрес пользователя';

CREATE TABLE IF NOT EXISTS requests(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR NOT NULL,
  requestor_id BIGINT NOT NULL,
  CONSTRAINT pk_requests PRIMARY KEY (id),
  CONSTRAINT fk_requests_to_users FOREIGN KEY (requestor_id) REFERENCES users (id) ON DELETE CASCADE
);
COMMENT ON TABLE requests IS 'Таблица запросов от пользователей';
COMMENT ON COLUMN requests.id IS 'Идентификатор записи';
COMMENT ON COLUMN requests.description IS 'Описание';
COMMENT ON COLUMN requests.requestor_id IS 'Идентификатор бронирующего';

CREATE TABLE IF NOT EXISTS  items(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  is_available BOOLEAN NOT NULL,
  owner_id BIGINT NOT NULL,
  request_id BIGINT,
  CONSTRAINT pk_items PRIMARY KEY (id),
  CONSTRAINT fk_items_to_users FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_items_to_requests FOREIGN KEY (request_id) REFERENCES requests (id) ON DELETE CASCADE
);
COMMENT ON TABLE items IS 'Таблица вещей';
COMMENT ON COLUMN items.id IS 'Идентификатор записи';
COMMENT ON COLUMN items.name IS 'Наименование';
COMMENT ON COLUMN items.description IS 'Описание';
COMMENT ON COLUMN items.is_available IS 'Признак доступности';
COMMENT ON COLUMN items.owner_id IS 'Идентификатор владельца';
COMMENT ON COLUMN items.request_id IS 'Идентификатор запроса';

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR NOT NULL,
  item_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  CONSTRAINT pk_comments PRIMARY KEY (id),
  CONSTRAINT fk_comments_to_items FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE,
  CONSTRAINT fk_comment_to_users FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);
COMMENT ON TABLE comments IS 'Таблица комментариев';
COMMENT ON COLUMN comments.id IS 'Идентификатор записи';
COMMENT ON COLUMN comments.text IS 'Содержимое';
COMMENT ON COLUMN comments.item_id IS 'Идентификатор вещи';
COMMENT ON COLUMN comments.author_id IS 'Идентификатор автора';

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  status VARCHAR,
  CONSTRAINT pk_booking PRIMARY KEY (id),
  CONSTRAINT fk_bookings_to_items FOREIGN KEY (item_id) REFERENCES items (id),
  CONSTRAINT fk_bookings_to_users FOREIGN KEY (booker_id) REFERENCES users (id)
);
COMMENT ON TABLE bookings IS 'Таблица бронирований';
COMMENT ON COLUMN bookings.id IS 'Идентификатор записи';
COMMENT ON COLUMN bookings.start_date IS 'Дата начала';
COMMENT ON COLUMN bookings.end_date IS 'Дата окончания';
COMMENT ON COLUMN bookings.item_id IS 'Идентификатор вещи';
COMMENT ON COLUMN bookings.booker_id IS 'Идентификатор бронирующего';
COMMENT ON COLUMN bookings.status IS 'Статус';