server.port: 9090

spring:
  sql.init.mode: always
  output.ansi.enabled: ALWAYS

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      default_schema: public

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/shareit
    username: shareit
    password: shareit

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{traceId}] %logger{36}: %msg%n"
  level:
    org.springframework:
      orm.jpa: TRACE
      transaction: TRACE
      transaction.interceptor: TRACE
      orm.jpa.JpaTransactionManager: TRACE
      org.zalando.logbook: TRACE
      ru.practicum.shareit: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health